### ISSUE TITLE
Setting up a screen w/o access to dev console

### ISSUE THREAD

**Issue by timdream** [mozilla/corsica#49]
Hi there,

There are a few spare TVs in Taipei and I would like to tune them into http://corsica.mozilla.io/ . We sideloaded Fennec into the Android TV but we couldn't attach a DevTools onto it, because there isn't a cable to connect it to the TV (as a phone would) nor it has a camera allow it to take a QR code.

I wonder if we want to add a minimum console into it? Or, `eval` the code from `location.hash`...?

**Comment by lonnen** [comment]
When the TV first connects it will should display "My name is {name}". If you give us the names of those televisions and a useful name we can remotely rename them.

In other offices we use a simple naming scheme:  {office}-{ambient,commons}-{#}

The "ambient" or "commons" designation is used to indicate if it can be seen from desks where people work. We avoid animations on these screens because they are distracting. The # is a simple linear ordering. Often we'll put a note on or near the TV indicating the name. Your office manager may have a labelmaker you can use for this purpose.

**Comment by timdream** [comment]
I'll leave you to configure it then. See mozilla/moz-corsica#78. Thanks.
